const keyDateCreate = "date_create";
const keyEmail = "email";
const keyPassword = "password";
const keyBirthYear = "birth_year";
const keyLoginType = "login_type";
const keyUser = "user";
const keyUid = "uid";
const String keyUserType = 'user_type';
const String keyAuthenticationWait = 'authentication_wait';
const String keyNickName = 'nick_name';
const String keyRecommendFriendUid = 'recommended_Friend_Uid';
const String keyTodayFriendUid = 'today_friend_uid';

const String keyImageUrl = 'image_url';
const String keyGender = 'gender';
const String keyCountry = 'country';
const String keyLocation = 'location';
const String keyAge = 'age';
const String keyMbti = 'mbti';
const String keyMannerScore = 'manner_score';
const String keyHobbies = 'hobbies';
const String keyLanguages = 'languages';

const keyPublicLetter = 'public_letter';
const keyContent = 'content';
const keyHashtags = 'hashtags';
const keyLikes = 'likes';
const keyReplyCount = 'replyCount';
const keyPublicLetterUid = 'public_letter_uid';