
import 'package:flutter/material.dart';

import '../const/value/enum.dart';

class UtilsEnum {

///로그인 타입
  static String getLoginTypeName(LoginType loginType) {
    switch (loginType) {
      case LoginType.apple:
        return 'Apple';
      case LoginType.kakao:
        return 'Kakao';
      case LoginType.naver:
        return 'Naver';
      case LoginType.google:
        return 'Google';
      case LoginType.email:
        return 'Email';
    }
  }

  /// 국가 라벨
  static String getCountryLabel(Country country, {String locale = 'en'}) {
    final label = _countryLabels[country];
    if (label != null) return label;
    return country.name;
  }

  /// 국가 전체 드롭다운 아이템
  static List<DropdownMenuItem<String>> buildCountryDropdownItems() {
    return Country.values.map((c) {
      return DropdownMenuItem<String>(
        value: c.name,
        child: Text(getCountryLabel(c)),
      );
    }).toList();
  }
}

const Map<Country, String> _countryLabels = {
  Country.AF: 'Afghanistan (افغانستان)',
  Country.AL: 'Albania (Shqipëria)',
  Country.DZ: 'Algeria (الجزائر)',
  Country.AS: 'American Samoa',
  Country.AD: 'Andorra',
  Country.AO: 'Angola',
  Country.AG: 'Antigua and Barbuda',
  Country.AR: 'Argentina',
  Country.AM: 'Armenia (Հայաստան)',
  Country.AU: 'Australia',
  Country.AT: 'Austria (Österreich)',
  Country.AZ: 'Azerbaijan (Azərbaycan)',
  Country.BS: 'Bahamas',
  Country.BH: 'Bahrain (البحرين)',
  Country.BD: 'Bangladesh (বাংলাদেশ)',
  Country.BB: 'Barbados',
  Country.BY: 'Belarus (Беларусь)',
  Country.BE: 'Belgium (België)',
  Country.BZ: 'Belize',
  Country.BJ: 'Benin (Bénin)',
  Country.BM: 'Bermuda',
  Country.BT: 'Bhutan (འབྲུག)',
  Country.BO: 'Bolivia',
  Country.BA: 'Bosnia and Herzegovina (Bosna i Hercegovina)',
  Country.BW: 'Botswana',
  Country.BR: 'Brazil (Brasil)',
  Country.BN: 'Brunei Darussalam',
  Country.BG: 'Bulgaria (България)',
  Country.BF: 'Burkina Faso',
  Country.BI: 'Burundi',
  Country.KH: 'Cambodia (កម្ពុជា)',
  Country.CM: 'Cameroon (Cameroun)',
  Country.CA: 'Canada',
  Country.CV: 'Cape Verde (Cabo Verde)',
  Country.KY: 'Cayman Islands',
  Country.CF: 'Central African Republic (République centrafricaine)',
  Country.TD: 'Chad (Tchad)',
  Country.CL: 'Chile',
  Country.CN: 'China (中国)',
  Country.CO: 'Colombia',
  Country.KM: 'Comoros (جزر القمر)',
  Country.CG: 'Congo',
  Country.CD: 'Congo, Democratic Republic of the',
  Country.CR: 'Costa Rica',
  Country.CI: 'Côte d\'Ivoire',
  Country.HR: 'Croatia (Hrvatska)',
  Country.CU: 'Cuba',
  Country.CY: 'Cyprus (Κύπρος)',
  Country.CZ: 'Czech Republic (Česká republika)',
  Country.DK: 'Denmark (Danmark)',
  Country.DJ: 'Djibouti (جيبوتي)',
  Country.DM: 'Dominica',
  Country.DO: 'Dominican Republic (República Dominicana)',
  Country.EC: 'Ecuador',
  Country.EG: 'Egypt (مصر)',
  Country.SV: 'El Salvador',
  Country.GQ: 'Equatorial Guinea (Guinea Ecuatorial)',
  Country.ER: 'Eritrea (ኤርትራ)',
  Country.EE: 'Estonia (Eesti)',
  Country.SZ: 'Eswatini',
  Country.ET: 'Ethiopia (ኢትዮጵያ)',
  Country.FJ: 'Fiji',
  Country.FI: 'Finland (Suomi)',
  Country.FR: 'France',
  Country.GA: 'Gabon',
  Country.GM: 'Gambia',
  Country.GE: 'Georgia (საქართველო)',
  Country.DE: 'Germany (Deutschland)',
  Country.GH: 'Ghana',
  Country.GR: 'Greece (Ελλάδα)',
  Country.GD: 'Grenada',
  Country.GT: 'Guatemala',
  Country.GN: 'Guinea (Guinée)',
  Country.GW: 'Guinea-Bissau (Guiné-Bissau)',
  Country.GY: 'Guyana',
  Country.HT: 'Haiti (Haïti)',
  Country.HN: 'Honduras',
  Country.HU: 'Hungary (Magyarország)',
  Country.IS: 'Iceland (Ísland)',
  Country.IN: 'India (भारत)',
  Country.ID: 'Indonesia (Indonesia)',
  Country.IR: 'Iran (ایران)',
  Country.IQ: 'Iraq (العراق)',
  Country.IE: 'Ireland',
  Country.IL: 'Israel (ישראל)',
  Country.IT: 'Italy (Italia)',
  Country.JM: 'Jamaica',
  Country.JP: 'Japan (日本)',
  Country.JO: 'Jordan (الأردن)',
  Country.KZ: 'Kazakhstan (Қазақстан)',
  Country.KE: 'Kenya',
  Country.KI: 'Kiribati',
  Country.KP: 'Korea (North) (조선민주주의인민공화국)',
  Country.KR: 'Korea (South) (대한민국)',
  Country.KW: 'Kuwait (الكويت)',
  Country.KG: 'Kyrgyzstan (Кыргызстан)',
  Country.LA: 'Laos (ລາວ)',
  Country.LV: 'Latvia (Latvija)',
  Country.LB: 'Lebanon (لبنان)',
  Country.LS: 'Lesotho',
  Country.LR: 'Liberia',
  Country.LY: 'Libya (ليبيا)',
  Country.LI: 'Liechtenstein',
  Country.LT: 'Lithuania (Lietuva)',
  Country.LU: 'Luxembourg (Luxembourg)',
  Country.MG: 'Madagascar (Madagasikara)',
  Country.MW: 'Malawi',
  Country.MY: 'Malaysia (Malaysia)',
  Country.MV: 'Maldives (Maldives)',
  Country.ML: 'Mali (Mali)',
  Country.MT: 'Malta',
  Country.MH: 'Marshall Islands',
  Country.MR: 'Mauritania (موريتانيا)',
  Country.MU: 'Mauritius (Moris)',
  Country.MX: 'Mexico (México)',
  Country.FM: 'Micronesia',
  Country.MD: 'Moldova (Republica Moldova)',
  Country.MC: 'Monaco (Monaco)',
  Country.MN: 'Mongolia (Монгол улс)',
  Country.ME: 'Montenegro (Crna Gora)',
  Country.MA: 'Morocco (المغرب)',
  Country.MZ: 'Mozambique (Moçambique)',
  Country.MM: 'Myanmar (Burma) (မြန်မာ)',
  Country.NA: 'Namibia',
  Country.NR: 'Nauru',
  Country.NP: 'Nepal (नेपाल)',
  Country.NL: 'Netherlands (Nederland)',
  Country.NZ: 'New Zealand',
  Country.NI: 'Nicaragua',
  Country.NE: 'Niger (Niger)',
  Country.NG: 'Nigeria (Nigeria)',
  Country.MK: 'North Macedonia (Северна Македонија)',
  Country.NO: 'Norway (Norge)',
  Country.OM: 'Oman (عمان)',
  Country.PK: 'Pakistan (پاکستان)',
  Country.PW: 'Palau',
  Country.PS: 'Palestine (فلسطين)',
  Country.PA: 'Panama',
  Country.PG: 'Papua New Guinea',
  Country.PY: 'Paraguay',
  Country.PE: 'Peru (Perú)',
  Country.PH: 'Philippines (Pilipinas)',
  Country.PL: 'Poland (Polska)',
  Country.PT: 'Portugal (Portugal)',
  Country.QA: 'Qatar (قطر)',
  Country.RO: 'Romania (România)',
  Country.RU: 'Russia (Россия)',
  Country.RW: 'Rwanda',
  Country.KN: 'Saint Kitts and Nevis',
  Country.LC: 'Saint Lucia',
  Country.VC: 'Saint Vincent and the Grenadines',
  Country.WS: 'Samoa',
  Country.SM: 'San Marino',
  Country.ST: 'Sao Tome and Principe',
  Country.SA: 'Saudi Arabia (السعودية)',
  Country.SN: 'Senegal (Sénégal)',
  Country.RS: 'Serbia (Србија)',
  Country.SC: 'Seychelles',
  Country.SL: 'Sierra Leone',
  Country.SG: 'Singapore (Singapore)',
  Country.SK: 'Slovakia (Slovensko)',
  Country.SI: 'Slovenia (Slovenija)',
  Country.SB: 'Solomon Islands',
  Country.SO: 'Somalia (Soomaaliya)',
  Country.ZA: 'South Africa (South Africa)',
  Country.SS: 'South Sudan',
  Country.ES: 'Spain (España)',
  Country.LK: 'Sri Lanka (ශ්‍රී ලංකාව)',
  Country.SD: 'Sudan (السودان)',
  Country.SR: 'Suriname',
  Country.SE: 'Sweden (Sverige)',
  Country.CH: 'Switzerland (Schweiz)',
  Country.SY: 'Syria (سوريا)',
  Country.TW: 'Taiwan (台灣)',
  Country.TJ: 'Tajikistan (Тоҷикистон)',
  Country.TZ: 'Tanzania (Tanzania)',
  Country.TH: 'Thailand (ประเทศไทย)',
  Country.TL: 'Timor-Leste',
  Country.TG: 'Togo',
  Country.TO: 'Tonga',
  Country.TT: 'Trinidad and Tobago',
  Country.TN: 'Tunisia (تونس)',
  Country.TR: 'Turkey (Türkiye)',
  Country.TM: 'Turkmenistan (Türkmenistan)',
  Country.TV: 'Tuvalu',
  Country.UG: 'Uganda',
  Country.UA: 'Ukraine (Україна)',
  Country.AE: 'United Arab Emirates (الإمارات)',
  Country.GB: 'United Kingdom',
  Country.US: 'United States',
  Country.UY: 'Uruguay',
  Country.UZ: 'Uzbekistan (O‘zbekiston)',
  Country.VU: 'Vanuatu',
  Country.VA: 'Vatican City (Città del Vaticano)',
  Country.VE: 'Venezuela',
  Country.VN: 'Vietnam (Việt Nam)',
  Country.YE: 'Yemen (اليمن)',
  Country.ZM: 'Zambia',
  Country.ZW: 'Zimbabwe',
};

