
import 'package:flutter/material.dart';

import '../const/value/enum.dart';

class UtilsEnum {

///로그인 타입
  static String getLoginTypeName(LoginType loginType) {
    switch (loginType) {
      case LoginType.apple:
        return 'Apple';
      case LoginType.kakao:
        return 'Kakao';
      case LoginType.naver:
        return 'Naver';
      case LoginType.google:
        return 'Google';
      case LoginType.email:
        return 'Email';
    }
  }

  /// 국가 라벨
  static String getCountryLabel(CountryIso2 country, {String locale = 'en'}) {
    final label = _countryLabels[country];
    if (label != null) return label;
    return country.name;
  }

  /// 국가 전체 드롭다운 아이템
  static List<DropdownMenuItem<String>> buildCountryDropdownItems() {
    return CountryIso2.values.map((c) {
      return DropdownMenuItem<String>(
        value: c.name,
        child: Text(getCountryLabel(c)),
      );
    }).toList();
  }
}

const Map<CountryIso2, String> _countryLabels = {
  CountryIso2.AF: 'Afghanistan (افغانستان)',
  CountryIso2.AL: 'Albania (Shqipëria)',
  CountryIso2.DZ: 'Algeria (الجزائر)',
  CountryIso2.AS: 'American Samoa',
  CountryIso2.AD: 'Andorra',
  CountryIso2.AO: 'Angola',
  CountryIso2.AG: 'Antigua and Barbuda',
  CountryIso2.AR: 'Argentina',
  CountryIso2.AM: 'Armenia (Հայաստան)',
  CountryIso2.AU: 'Australia',
  CountryIso2.AT: 'Austria (Österreich)',
  CountryIso2.AZ: 'Azerbaijan (Azərbaycan)',
  CountryIso2.BS: 'Bahamas',
  CountryIso2.BH: 'Bahrain (البحرين)',
  CountryIso2.BD: 'Bangladesh (বাংলাদেশ)',
  CountryIso2.BB: 'Barbados',
  CountryIso2.BY: 'Belarus (Беларусь)',
  CountryIso2.BE: 'Belgium (België)',
  CountryIso2.BZ: 'Belize',
  CountryIso2.BJ: 'Benin (Bénin)',
  CountryIso2.BM: 'Bermuda',
  CountryIso2.BT: 'Bhutan (འབྲུག)',
  CountryIso2.BO: 'Bolivia',
  CountryIso2.BA: 'Bosnia and Herzegovina (Bosna i Hercegovina)',
  CountryIso2.BW: 'Botswana',
  CountryIso2.BR: 'Brazil (Brasil)',
  CountryIso2.BN: 'Brunei Darussalam',
  CountryIso2.BG: 'Bulgaria (България)',
  CountryIso2.BF: 'Burkina Faso',
  CountryIso2.BI: 'Burundi',
  CountryIso2.KH: 'Cambodia (កម្ពុជា)',
  CountryIso2.CM: 'Cameroon (Cameroun)',
  CountryIso2.CA: 'Canada',
  CountryIso2.CV: 'Cape Verde (Cabo Verde)',
  CountryIso2.KY: 'Cayman Islands',
  CountryIso2.CF: 'Central African Republic (République centrafricaine)',
  CountryIso2.TD: 'Chad (Tchad)',
  CountryIso2.CL: 'Chile',
  CountryIso2.CN: 'China (中国)',
  CountryIso2.CO: 'Colombia',
  CountryIso2.KM: 'Comoros (جزر القمر)',
  CountryIso2.CG: 'Congo',
  CountryIso2.CD: 'Congo, Democratic Republic of the',
  CountryIso2.CR: 'Costa Rica',
  CountryIso2.CI: 'Côte d\'Ivoire',
  CountryIso2.HR: 'Croatia (Hrvatska)',
  CountryIso2.CU: 'Cuba',
  CountryIso2.CY: 'Cyprus (Κύπρος)',
  CountryIso2.CZ: 'Czech Republic (Česká republika)',
  CountryIso2.DK: 'Denmark (Danmark)',
  CountryIso2.DJ: 'Djibouti (جيبوتي)',
  CountryIso2.DM: 'Dominica',
  CountryIso2.DO: 'Dominican Republic (República Dominicana)',
  CountryIso2.EC: 'Ecuador',
  CountryIso2.EG: 'Egypt (مصر)',
  CountryIso2.SV: 'El Salvador',
  CountryIso2.GQ: 'Equatorial Guinea (Guinea Ecuatorial)',
  CountryIso2.ER: 'Eritrea (ኤርትራ)',
  CountryIso2.EE: 'Estonia (Eesti)',
  CountryIso2.SZ: 'Eswatini',
  CountryIso2.ET: 'Ethiopia (ኢትዮጵያ)',
  CountryIso2.FJ: 'Fiji',
  CountryIso2.FI: 'Finland (Suomi)',
  CountryIso2.FR: 'France',
  CountryIso2.GA: 'Gabon',
  CountryIso2.GM: 'Gambia',
  CountryIso2.GE: 'Georgia (საქართველო)',
  CountryIso2.DE: 'Germany (Deutschland)',
  CountryIso2.GH: 'Ghana',
  CountryIso2.GR: 'Greece (Ελλάδα)',
  CountryIso2.GD: 'Grenada',
  CountryIso2.GT: 'Guatemala',
  CountryIso2.GN: 'Guinea (Guinée)',
  CountryIso2.GW: 'Guinea-Bissau (Guiné-Bissau)',
  CountryIso2.GY: 'Guyana',
  CountryIso2.HT: 'Haiti (Haïti)',
  CountryIso2.HN: 'Honduras',
  CountryIso2.HU: 'Hungary (Magyarország)',
  CountryIso2.IS: 'Iceland (Ísland)',
  CountryIso2.IN: 'India (भारत)',
  CountryIso2.ID: 'Indonesia (Indonesia)',
  CountryIso2.IR: 'Iran (ایران)',
  CountryIso2.IQ: 'Iraq (العراق)',
  CountryIso2.IE: 'Ireland',
  CountryIso2.IL: 'Israel (ישראל)',
  CountryIso2.IT: 'Italy (Italia)',
  CountryIso2.JM: 'Jamaica',
  CountryIso2.JP: 'Japan (日本)',
  CountryIso2.JO: 'Jordan (الأردن)',
  CountryIso2.KZ: 'Kazakhstan (Қазақстан)',
  CountryIso2.KE: 'Kenya',
  CountryIso2.KI: 'Kiribati',
  CountryIso2.KP: 'Korea (North) (조선민주주의인민공화국)',
  CountryIso2.KR: 'Korea (South) (대한민국)',
  CountryIso2.KW: 'Kuwait (الكويت)',
  CountryIso2.KG: 'Kyrgyzstan (Кыргызстан)',
  CountryIso2.LA: 'Laos (ລາວ)',
  CountryIso2.LV: 'Latvia (Latvija)',
  CountryIso2.LB: 'Lebanon (لبنان)',
  CountryIso2.LS: 'Lesotho',
  CountryIso2.LR: 'Liberia',
  CountryIso2.LY: 'Libya (ليبيا)',
  CountryIso2.LI: 'Liechtenstein',
  CountryIso2.LT: 'Lithuania (Lietuva)',
  CountryIso2.LU: 'Luxembourg (Luxembourg)',
  CountryIso2.MG: 'Madagascar (Madagasikara)',
  CountryIso2.MW: 'Malawi',
  CountryIso2.MY: 'Malaysia (Malaysia)',
  CountryIso2.MV: 'Maldives (Maldives)',
  CountryIso2.ML: 'Mali (Mali)',
  CountryIso2.MT: 'Malta',
  CountryIso2.MH: 'Marshall Islands',
  CountryIso2.MR: 'Mauritania (موريتانيا)',
  CountryIso2.MU: 'Mauritius (Moris)',
  CountryIso2.MX: 'Mexico (México)',
  CountryIso2.FM: 'Micronesia',
  CountryIso2.MD: 'Moldova (Republica Moldova)',
  CountryIso2.MC: 'Monaco (Monaco)',
  CountryIso2.MN: 'Mongolia (Монгол улс)',
  CountryIso2.ME: 'Montenegro (Crna Gora)',
  CountryIso2.MA: 'Morocco (المغرب)',
  CountryIso2.MZ: 'Mozambique (Moçambique)',
  CountryIso2.MM: 'Myanmar (Burma) (မြန်မာ)',
  CountryIso2.NA: 'Namibia',
  CountryIso2.NR: 'Nauru',
  CountryIso2.NP: 'Nepal (नेपाल)',
  CountryIso2.NL: 'Netherlands (Nederland)',
  CountryIso2.NZ: 'New Zealand',
  CountryIso2.NI: 'Nicaragua',
  CountryIso2.NE: 'Niger (Niger)',
  CountryIso2.NG: 'Nigeria (Nigeria)',
  CountryIso2.MK: 'North Macedonia (Северна Македонија)',
  CountryIso2.NO: 'Norway (Norge)',
  CountryIso2.OM: 'Oman (عمان)',
  CountryIso2.PK: 'Pakistan (پاکستان)',
  CountryIso2.PW: 'Palau',
  CountryIso2.PS: 'Palestine (فلسطين)',
  CountryIso2.PA: 'Panama',
  CountryIso2.PG: 'Papua New Guinea',
  CountryIso2.PY: 'Paraguay',
  CountryIso2.PE: 'Peru (Perú)',
  CountryIso2.PH: 'Philippines (Pilipinas)',
  CountryIso2.PL: 'Poland (Polska)',
  CountryIso2.PT: 'Portugal (Portugal)',
  CountryIso2.QA: 'Qatar (قطر)',
  CountryIso2.RO: 'Romania (România)',
  CountryIso2.RU: 'Russia (Россия)',
  CountryIso2.RW: 'Rwanda',
  CountryIso2.KN: 'Saint Kitts and Nevis',
  CountryIso2.LC: 'Saint Lucia',
  CountryIso2.VC: 'Saint Vincent and the Grenadines',
  CountryIso2.WS: 'Samoa',
  CountryIso2.SM: 'San Marino',
  CountryIso2.ST: 'Sao Tome and Principe',
  CountryIso2.SA: 'Saudi Arabia (السعودية)',
  CountryIso2.SN: 'Senegal (Sénégal)',
  CountryIso2.RS: 'Serbia (Србија)',
  CountryIso2.SC: 'Seychelles',
  CountryIso2.SL: 'Sierra Leone',
  CountryIso2.SG: 'Singapore (Singapore)',
  CountryIso2.SK: 'Slovakia (Slovensko)',
  CountryIso2.SI: 'Slovenia (Slovenija)',
  CountryIso2.SB: 'Solomon Islands',
  CountryIso2.SO: 'Somalia (Soomaaliya)',
  CountryIso2.ZA: 'South Africa (South Africa)',
  CountryIso2.SS: 'South Sudan',
  CountryIso2.ES: 'Spain (España)',
  CountryIso2.LK: 'Sri Lanka (ශ්‍රී ලංකාව)',
  CountryIso2.SD: 'Sudan (السودان)',
  CountryIso2.SR: 'Suriname',
  CountryIso2.SE: 'Sweden (Sverige)',
  CountryIso2.CH: 'Switzerland (Schweiz)',
  CountryIso2.SY: 'Syria (سوريا)',
  CountryIso2.TW: 'Taiwan (台灣)',
  CountryIso2.TJ: 'Tajikistan (Тоҷикистон)',
  CountryIso2.TZ: 'Tanzania (Tanzania)',
  CountryIso2.TH: 'Thailand (ประเทศไทย)',
  CountryIso2.TL: 'Timor-Leste',
  CountryIso2.TG: 'Togo',
  CountryIso2.TO: 'Tonga',
  CountryIso2.TT: 'Trinidad and Tobago',
  CountryIso2.TN: 'Tunisia (تونس)',
  CountryIso2.TR: 'Turkey (Türkiye)',
  CountryIso2.TM: 'Turkmenistan (Türkmenistan)',
  CountryIso2.TV: 'Tuvalu',
  CountryIso2.UG: 'Uganda',
  CountryIso2.UA: 'Ukraine (Україна)',
  CountryIso2.AE: 'United Arab Emirates (الإمارات)',
  CountryIso2.GB: 'United Kingdom',
  CountryIso2.US: 'United States',
  CountryIso2.UY: 'Uruguay',
  CountryIso2.UZ: 'Uzbekistan (O‘zbekiston)',
  CountryIso2.VU: 'Vanuatu',
  CountryIso2.VA: 'Vatican City (Città del Vaticano)',
  CountryIso2.VE: 'Venezuela',
  CountryIso2.VN: 'Vietnam (Việt Nam)',
  CountryIso2.YE: 'Yemen (اليمن)',
  CountryIso2.ZM: 'Zambia',
  CountryIso2.ZW: 'Zimbabwe',
};

